export const colorOptions = [
  { value: '#FF0000', label: 'Red' },
  { value: '#00FF00', label: 'Lime' },
  { value: '#0000FF', label: 'Blue' },
  { value: '#FFFF00', label: 'Yellow' },
  { value: '#FF00FF', label: 'Fuchsia' },
  { value: '#00FFFF', label: 'Aqua' },
  { value: '#FFA500', label: 'Orange' },
  { value: '#800080', label: 'Purple' },
  { value: '#008000', label: 'Green' },
  { value: '#800000', label: 'Maroon' },
  { value: '#008080', label: 'Teal' },
  { value: '#000080', label: 'Navy' },
  { value: '#FFFFCC', label: 'Light Yellow' },
  { value: '#FFCC99', label: 'Peach' },
  { value: '#FF6666', label: 'Salmon' },
  { value: '#FF3366', label: 'Watermelon' },
  { value: '#CCFFCC', label: 'Pale Green' },
  { value: '#99FF99', label: 'Mint Green' },
  { value: '#66FF99', label: 'Spring Green' },
  { value: '#66CC99', label: 'Seafoam Green' },
  { value: '#339966', label: 'Forest Green' },
  { value: '#336666', label: 'Teal Green' },
  // Adicione mais cores conforme necessário
  { value: '#CCCCFF', label: 'Periwinkle' },
  { value: '#CC99FF', label: 'Lavender' },
  { value: '#9966FF', label: 'Royal Purple' },
  { value: '#6633FF', label: 'Deep Purple' },
  { value: '#3300FF', label: 'Blue Violet' },
  { value: '#FF99CC', label: 'Pink' },
  { value: '#FF6699', label: 'Hot Pink' },
  { value: '#FF3366', label: 'Coral' },
  { value: '#FF0033', label: 'Ruby Red' },
  { value: '#FFCCCC', label: 'Light Salmon' },
  { value: '#FF9999', label: 'Light Coral' },
  { value: '#FF6666', label: 'Indian Red' },
  { value: '#FF3333', label: 'Fire Brick' },
  { value: '#CC0000', label: 'Dark Red' },
  { value: '#FFD700', label: 'Gold' },
  { value: '#FFB90F', label: 'Dark Goldenrod' },
  { value: '#FFA500', label: 'Orange' },
  { value: '#FF8C00', label: 'Dark Orange' },
  { value: '#FF4500', label: 'Orange Red' },
  { value: '#FF6347', label: 'Tomato' },
  { value: '#FF7F50', label: 'Coral' },
  { value: '#FA8072', label: 'Salmon' },
  { value: '#E9967A', label: 'Dark Salmon' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFE4B5', label: 'Moccasin' },
  { value: '#FFDEAD', label: 'Navajo White' },
  { value: '#FFF8DC', label: 'Cornsilk' },
  { value: '#FFE4C4', label: 'Bisque' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFA07A', label: 'Light Salmon' },
  { value: '#FF7F50', label: 'Coral' },
  { value: '#FF6347', label: 'Tomato' },
  { value: '#FF4500', label: 'Orange Red' },
  { value: '#FF8C00', label: 'Dark Orange' },
  { value: '#FFD700', label: 'Gold' },
  { value: '#FFFFE0', label: 'Light Yellow' },
  { value: '#FFFACD', label: 'Lemon Chiffon' },
  { value: '#FAFAD2', label: 'Light Goldenrod Yellow' },
  { value: '#FFEFD5', label: 'Papaya Whip' },
  { value: '#FFE4B5', label: 'Moccasin' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFDEAD', label: 'Navajo White' },
  { value: '#FFF8DC', label: 'Cornsilk' },
  { value: '#FFE4C4', label: 'Bisque' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFA07A', label: 'Light Salmon' },
  { value: '#FF7F50', label: 'Coral' },
  { value: '#FF6347', label: 'Tomato' },
  { value: '#FF4500', label: 'Orange Red' },
  { value: '#FF8C00', label: 'Dark Orange' },
  { value: '#FFD700', label: 'Gold' },
  { value: '#FFFFE0', label: 'Light Yellow' },
  { value: '#FFFACD', label: 'Lemon Chiffon' },
  { value: '#FAFAD2', label: 'Light Goldenrod Yellow' },
  { value: '#FFEFD5', label: 'Papaya Whip' },
  { value: '#FFE4B5', label: 'Moccasin' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFDEAD', label: 'Navajo White' },
  { value: '#FFF8DC', label: 'Cornsilk' },
  { value: '#FFE4C4', label: 'Bisque' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFA07A', label: 'Light Salmon' },
  { value: '#FF7F50', label: 'Coral' },
  { value: '#FF6347', label: 'Tomato' },
  { value: '#FF4500', label: 'Orange Red' },
  { value: '#FF8C00', label: 'Dark Orange' },
  { value: '#FFD700', label: 'Gold' },
  { value: '#FFFFE0', label: 'Light Yellow' },
  { value: '#FFFACD', label: 'Lemon Chiffon' },
  { value: '#FAFAD2', label: 'Light Goldenrod Yellow' },
  { value: '#FFEFD5', label: 'Papaya Whip' },
  { value: '#FFE4B5', label: 'Moccasin' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFDEAD', label: 'Navajo White' },
  { value: '#FFF8DC', label: 'Cornsilk' },
  { value: '#FFE4C4', label: 'Bisque' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFA07A', label: 'Light Salmon' },
  { value: '#FF7F50', label: 'Coral' },
  { value: '#FF6347', label: 'Tomato' },
  { value: '#FF4500', label: 'Orange Red' },
  { value: '#FF8C00', label: 'Dark Orange' },
  { value: '#FFD700', label: 'Gold' },
  { value: '#FFFFE0', label: 'Light Yellow' },
  { value: '#FFFACD', label: 'Lemon Chiffon' },
  { value: '#FAFAD2', label: 'Light Goldenrod Yellow' },
  { value: '#FFEFD5', label: 'Papaya Whip' },
  { value: '#FFE4B5', label: 'Moccasin' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFDEAD', label: 'Navajo White' },
  { value: '#FFF8DC', label: 'Cornsilk' },
  { value: '#FFE4C4', label: 'Bisque' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFA07A', label: 'Light Salmon' },
  { value: '#FF7F50', label: 'Coral' },
  { value: '#FF6347', label: 'Tomato' },
  { value: '#FF4500', label: 'Orange Red' },
  { value: '#FF8C00', label: 'Dark Orange' },
  { value: '#FFD700', label: 'Gold' },
  { value: '#FFFFE0', label: 'Light Yellow' },
  { value: '#FFFACD', label: 'Lemon Chiffon' },
  { value: '#FAFAD2', label: 'Light Goldenrod Yellow' },
  { value: '#FFEFD5', label: 'Papaya Whip' },
  { value: '#FFE4B5', label: 'Moccasin' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFDEAD', label: 'Navajo White' },
  { value: '#FFF8DC', label: 'Cornsilk' },
  { value: '#FFE4C4', label: 'Bisque' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFA07A', label: 'Light Salmon' },
  { value: '#FF7F50', label: 'Coral' },
  { value: '#FF6347', label: 'Tomato' },
  { value: '#FF4500', label: 'Orange Red' },
  { value: '#FF8C00', label: 'Dark Orange' },
  { value: '#FFD700', label: 'Gold' },
  { value: '#FFFFE0', label: 'Light Yellow' },
  { value: '#FFFACD', label: 'Lemon Chiffon' },
  { value: '#FAFAD2', label: 'Light Goldenrod Yellow' },
  { value: '#FFEFD5', label: 'Papaya Whip' },
  { value: '#FFE4B5', label: 'Moccasin' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFDEAD', label: 'Navajo White' },
  { value: '#FFF8DC', label: 'Cornsilk' },
  { value: '#FFE4C4', label: 'Bisque' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFA07A', label: 'Light Salmon' },
  { value: '#FF7F50', label: 'Coral' },
  { value: '#FF6347', label: 'Tomato' },
  { value: '#FF4500', label: 'Orange Red' },
  { value: '#FF8C00', label: 'Dark Orange' },
  { value: '#FFD700', label: 'Gold' },
  { value: '#FFFFE0', label: 'Light Yellow' },
  { value: '#FFFACD', label: 'Lemon Chiffon' },
  { value: '#FAFAD2', label: 'Light Goldenrod Yellow' },
  { value: '#FFEFD5', label: 'Papaya Whip' },
  { value: '#FFE4B5', label: 'Moccasin' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFDEAD', label: 'Navajo White' },
  { value: '#FFF8DC', label: 'Cornsilk' },
  { value: '#FFE4C4', label: 'Bisque' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFA07A', label: 'Light Salmon' },
  { value: '#FF7F50', label: 'Coral' },
  { value: '#FF6347', label: 'Tomato' },
  { value: '#FF4500', label: 'Orange Red' },
  { value: '#FF8C00', label: 'Dark Orange' },
  { value: '#FFD700', label: 'Gold' },
  { value: '#FFFFE0', label: 'Light Yellow' },
  { value: '#FFFACD', label: 'Lemon Chiffon' },
  { value: '#FAFAD2', label: 'Light Goldenrod Yellow' },
  { value: '#FFEFD5', label: 'Papaya Whip' },
  { value: '#FFE4B5', label: 'Moccasin' },
  { value: '#FFDAB9', label: 'Peachpuff' },
  { value: '#FFDEAD', label: 'Navajo White' },
  { value: '#FFF8DC', label: 'Cornsilk' },
  { value: '#FFE4C4', label: 'Bisque' },
]
